version: "3"

services:

  web:
    container_name: ${COMPOSE_PROJECT_NAME}
    image: jupyter_tensorflow
    build:
      context: ./images/web
      args:
        SSH_PSWD: ${SSH_PSWD}
    restart: ${RESTART}
    environment:
      RESTARTABLE: 'yes'
    networks:
      - network

networks:

  network:
    external:
      name: ${NETWORK}
